export const ORG_SECTIONS = [
  {
    key: "settings",
    label: "Settings",
    singular: "settings",
    path: "/organization",
    to: "/organization/settings",
    hint: "Organization name and tenant settings.",
  },
  {
    key: "audit",
    label: "Audit log",
    singular: "audit event",
    path: "/audit-logs",
    to: "/organization/audit",
    hint: "Immutable record of create, edit, and custody changes.",
  },
  {
    key: "designations",
    label: "Designations",
    singular: "designation",
    path: "/designations",
    to: "/organization/designations",
    hint: "Job titles that can be assigned to users.",
  },
  {
    key: "departments",
    label: "Departments",
    singular: "department",
    path: "/departments",
    to: "/organization/departments",
    hint: "Teams and business units that own or use assets.",
  },
  {
    key: "locations",
    label: "Locations",
    singular: "location",
    path: "/locations",
    to: "/organization/locations",
    hint: "Offices, warehouses, sites, and other physical places.",
  },
  {
    key: "projects",
    label: "Projects",
    singular: "project",
    path: "/projects",
    to: "/organization/projects",
    hint: "Projects and sites that assets can be linked to.",
  },
  {
    key: "categories",
    label: "Categories",
    singular: "category",
    path: "/categories",
    to: "/organization/categories",
    hint: "Types used to group assets in the register.",
  },
  {
    key: "manufacturers",
    label: "Manufacturers",
    singular: "manufacturer",
    path: "/manufacturers",
    to: "/organization/manufacturers",
    hint: "Brands and makers linked to assets in the register.",
  },
  {
    key: "suppliers",
    label: "Suppliers",
    singular: "supplier",
    path: "/suppliers",
    to: "/organization/suppliers",
    hint: "Vendors that supply assets to the organization.",
  },
];

